#!/bin/bash

read -p "Device Hostname: " hostname_
read -p "Device IP: " ip_
if grep -q ${hostname_} /etc/hosts; then
	echo "Hostname exists...overwriting..."
        sudo sh -c "sed -i '/${hostname_}/d' /etc/hosts" #deleting

	sudo sh -c "echo '${ip_} ${hostname_}' >> /etc/hosts"
	echo "Hostname added"
	
else
	sudo sh -c "echo '${ip_} ${hostname_}' >> /etc/hosts"
	echo "Hostname added"
fi
cd ..

"$SHELL"
